# Generated by Django 4.2.4 on 2023-08-13 09:22

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('image_carousel', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('bulleted_list', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock())), ('image_text', wagtail.blocks.StructBlock([('image1', wagtail.images.blocks.ImageChooserBlock()), ('caption1', wagtail.blocks.CharBlock(max_length=100, required=False)), ('image2', wagtail.images.blocks.ImageChooserBlock()), ('caption2', wagtail.blocks.CharBlock(max_length=100, required=False))])), ('quote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.RichTextBlock()), ('author', wagtail.blocks.CharBlock())]))], blank=True, use_json_field=True),
        ),
    ]
