# Generated by Django 4.2.4 on 2023-08-17 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='post date'),
        ),
    ]
